<div class="row">
    
     <div class="col-md-6 col-md-offset-3">

        <div class="well formEspacoTopo">
            
             <h3 class="text-center">Editar Departamento</h3>
            
            <?php
            $form = $this->form;

            $form->setAttribute('action', $this->url('assistente-interna', array('controller' => 'departamentos', 'action' => 'edit')));

            $form->prepare();
            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('id')); ?>
            
            <div class="form-group">
            <?php 
                echo $this->formInput($form->get('nome')); 
                echo $this->formElementErrors($form->get('nome'), array('class' => 'error'));
            ?>
            </div>
             
            <div class="form-group">
            <?php 
                echo $this->formInput($form->get('sigla')); 
                echo $this->formElementErrors($form->get('sigla'), array('class' => 'error'));
            ?>
            </div>
             
            <?php 
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
            ?>

        </div> 
    </div>

</div>