

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Lista de Departamentos
        <small>Abaixo são listados todos os departamentos cadastrados no sistema</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">



    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Lista</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i></button>
            </div>
        </div>


        <?php
        $flash = $this->flashMessenger();
        $flash->setMessageOpenFormat('<div%s">
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
                ->setMessageSeparatorString('</li><li>')
                ->setMessageCloseString('</li></ul></div>');

        echo $flash->render('error', array('alert', 'alert-dismissible', 'alert-danger'));
        echo $flash->render('info', array('alert', 'alert-dismissible', 'alert-info'));
        echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
        echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
        ?>

        <div class="well">
           
             <div class="col-md-9"> 
                <a href="<?php echo $this->url('assistente', array('controller' => 'departamentos', 'action' => 'new')); ?>" class="btn btn-primary">Novo</a>
            </div>

            <div class="col-md-3">

                <form class="form-inline" method="POST" action="<?php echo $this->url('assistente', array('controller' => 'departamentos', 'action' => 'filtro')); ?>">
                    <div class="form-group">
                        <input type="text" class="form-control" name="busca" id="busca" placeholder="Busca por nome">
                    </div>
                    <input type="submit" class="btn btn-primary" value="Buscar"> 
                </form>

            </div>    



            <table class="table table-striped tabelaListar">
                <thead>
                <th>Id</th>
                <th>Nome</th>
                <th>Sigla</th>
                <th>Ação</th>
                </thead>
                <tbody>
                    <?php foreach ($this->data as $data): ?>
                        <tr>
                            <td><?php echo $data->getId(); ?></td>
                            <td><?php echo $data->getNome(); ?></td>
                            <td><?php echo $data->getSigla(); ?></td>
                            <td>
                                <a href="<?php echo $this->url('assistente-interna', array('controller' => 'departamentos', 'action' => 'edit', 'id' => $data->getId())) ?>" class="btn btn-default">Editar</a> | 
                                <a href="<?php echo $this->url('assistente-interna', array('controller' => 'departamentos', 'action' => 'delete', 'id' => $data->getId())) ?>" class="btn btn-default">Excluir</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>    
        <br />


        <?php echo $this->paginationControl($this->data, 'Sliding', 'paginator'); ?>
    </div>

    <!-- /.box-body -->
</div>
<!-- /.box -->

</section>











