<div class="row">

    <div class="col-md-4 col-md-offset-4">

        <div class="well formEspacoTopo">

            <div class="col-md-8  col-md-offset-3">
            <p><img src="<?php echo $this->basePath() . '/images/logo.png' ?>" width="80" height="80" class="logoLogin"></p>
            </div>
            
            <h4 class="text-center">Assitente Corag</h4> <br /><br />

            <?php
            if ($this->error):
                echo "<p>Usuário ou senha inválidos</p>";
            endif;


            $form = $this->form;

            $form->setAttribute('action', $this->url('assistente-auth'));

            $form->prepare();
            echo $this->form()->openTag($form);
            ?>
            <div class="form-group">
                <?php echo $this->formRow($form->get('email')); ?>
            </div>
            <div class="form-group">
                <?php echo $this->formRow($form->get('password')) . '<br />'; ?>
            </div>    
            <?php echo $this->formSubmit($form->get('submit')); ?>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>      
</div>    