
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Detalhes do Usuário
        <small>Abaixo serão listados todos o dados do usuário.</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li> 
        <li class="active">Dashboard</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Detalhes</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i></button>
            </div>
        </div>


        <div class="box-body">



            <div class="row">
                <div class="col-md-12">
                    <!-- Widget: user widget style 1 -->
                    <div class="box box-widget widget-user-2">
                        <!-- Add the bg color to the header using any of the bg-* classes -->
                        <div class="widget-user-header bg-yellow">
                            <div class="widget-user-image">
                                <img class="img-circle" src="<?php echo "/fotos/" . str_replace(" ", "_", $this->data->getFoto()); ?>" alt="User Avatar">
                            </div>
                            <!-- /.widget-user-image -->
                            <h3 class="widget-user-username">Nadia Carmichael</h3>
                            <h5 class="widget-user-desc">Lead Developer</h5>
                        </div>
                        <div class="box-footer no-padding">
                            <ul class="nav nav-stacked">
                                <li><a href="#"><?php echo "<strong>Matricula:</strong> " . $this->data->getMatricula() ?></a></li>
                                <li><a href="#"><?php echo "<strong>Nome:</strong> " . $this->data->getNome(); ?></a></li>
                                <li><a href="#"><?php echo "<strong>Data da Admissão:</strong> " . $this->data->getAdmissao(); ?></a></li>
                                <li><a href="#"><?php echo "<strong>Departamento:</strong> " . $this->data->getDepartamento(); ?></a></li>
                                <li><a href="#"><?php echo "<strong>Data de Nascimento:</strong> " . $this->data->getDataNascimento(); ?></a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- /.widget-user -->
                </div>
                <!-- /.col -->

            </div>


        </div>
        <!-- /.box-body -->

    </div>
    <!-- /.box -->

</section>
















